Main view
kacus/CC-Chess pull request #17
Opened 2021-02-15 17:44 UTC by pkol92

Start game after btn start clicked

2021-02-15 21:06 UTC, Skorcese requested changes

2021-02-15 21:06 UTC, Skorcese commented on src/ts/App/Views/menu.ts
> +        form_action.innerText = "GAME WARIANT";
GAME MODE or GAME VARIANT?

2021-02-16 15:48 UTC, pkol92 commented on src/ts/App/Views/menu.ts
> +        form_action.innerText = "GAME WARIANT";
I changed it to game mode

2021-02-16 16:51 UTC, Skorcese approved these changes

2021-02-16 17:10 UTC, merged