Add actions to menu
kacus/CC-Chess pull request #18
Opened 2021-02-15 19:29 UTC by cwaniakobezczel

2021-02-15 21:31 UTC, Skorcese requested changes

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/App.ts
> +    revert_btn.addEventListener('click', (e)=>{
In javascript/typescript we use the camelCase naming convention, not the snake_case which is used in python

Change it to `revertBtn`

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +    this.view.timeDispaly(5, EColor.White);
Let's fix the typo in the name `timeDispaly `-> `timeDisplay`

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +    let btn_box = document.getElementById("start__button")!;
`const btnBox`

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +    let timeElement = document.getElementById("range");
`const timeElement`

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +      let timeValue = (<HTMLInputElement>document.getElementById("range"))
`let timeValue = parseInt((<HTMLInputElement>document.getElementById("range")).value);`
And delete the `x` variable while changing it to `timeValue` in other places

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +      console.log(x + "value");
Let's not leave the console.logs in PRs

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +    // setTimeout(() => {
Leftover comment

2021-02-15 21:31 UTC, Skorcese commented on src/ts/App/Views/boardView.ts
> +      const obj = document.querySelector(".stage:nth-child(3) > .time")!;
All of this could be simplified, according to DRY (Don't Repeat Yourself)

```
const nthChild = color === EColor.White ? 3 : 1;

const timer = document.querySelector(`.stage:nth-child(${nthChild}) > .time`)!;
const min = Math.floor(time / 60);
const sec = time % 60;

const shouldAppendZero = (timeUnit: number): string =>
     (''+timeUnit).length === 1 ? `0${timeUnit}` : timeUnit.toString();

timer.innerHTML = `${shouldAppendZero(min)}:${shouldAppendZero(sec)} min`;
```

2021-02-16 12:27 UTC, kacus requested changes

2021-02-16 12:27 UTC, kacus commented on src/ts/App/Controllers/boardController.ts
> -    }, 5000);
this debugging information is no longer needed

2021-02-16 12:27 UTC, kacus commented on src/ts/App/Views/tabsView.ts
>      document.getElementById(aTag.href.split("#")[1])!.className += " active";
this line is little complicated, try to split it up. Also I find using element.classList.add("className") more elegant than appending string(add method also deletes duplicates).
https://developer.mozilla.org/pl/docs/Web/API/Element/classList

2021-02-16 12:27 UTC, kacus commented on src/ts/App/Views/boardView.ts
> +    const shouldAppendZero = (timeUnit: number): string =>
Name of this function suggest it returns boolean value, what can be little confusing. I suggest to rename it to be more specific.

2021-02-16 16:49 UTC, Skorcese approved these changes

2021-02-16 16:49 UTC, Skorcese commented on src/ts/App/Views/boardView.ts
> +    const shouldAppendZero = (timeUnit: number): string =>
`appendZero` or `appendZeroIfNeeded`

2021-02-16 17:01 UTC, merged