Feature/chessboard controller
kacus/CC-Chess pull request #6
Opened 2021-01-31 13:11 UTC by kacus

Add basic chess functionality

2021-01-31 14:58 UTC, Skorcese requested changes

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +        this.view.init(this.parent, this.board, this.clickOnField.bind(this));
Try to stop using "bind" with TS. "bind" returns any. If you take a look into the definition of bind:

    bind (thisArg: any, ...anyArray: any[]) : any

That means that calling bind on a function will cause you to completely lose any type safety of the original function signature in case you want to use these types further

Try with an arrow fn instead

https://hamednourhani.gitbooks.io/typescript-book/content/docs/tips/bind.html

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +            if (clicked) {
That's quite a big if chain making it hard to read/debug. Try to simplify it, so that there are no nested ifs

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardInterface.ts
> +    possibleMovesFor(pos: Field): Array<Field>;
Stay consistent with declaring types

Either `Array<Array<IFigure>>` and `Array<Field>` (less readable IMO)
OR `IFigure[][]` and `Field[]`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +import KingModel from './kingModel';
To avoid multiple imports, make an index.ts file where you'd import & export all models, then
`import * from './index'` if it's a default import
`import { KingModel, KnightModel, RookModel, TowerModel, BishopModel, QueenModel } from './index'` or a named import

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +                if (row < 1 || row > 8) break;
That's what I've been told when I was being reviewed: Always use brackets with Ifs - improves readability

```
if (row < 1 || row > 8) {
    break;
}
```

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +                let new_pos: Field = [row, col];
This should be a `const` - new_pos is not being reassigned anywhere

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +        let moves: Array<Field> = [];
This should be a `const` - moves is not being reassigned anywhere. In general, arrays should always be a `const` variable

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +        let attacks: Array<Field> = [];
`const`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +            [null, null, null, null, null, null, null, null],
`Array(8).fill(null)` does the same job. Even better, you could make it as a constant at the top of the file and pass it here

`const EMPTY_ROW = Array(8).fill(null);`

then

`this.board = [ [black models here], EMPTY_ROW, EMPTY_ROW, etc..., [white models here]]`

Even better!

`this.board = [ [black models here], ...(Array(6).fill(EMPTY_ROW)), [ white models here ]];`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/figureInterface.ts
> +export type ListOfVectors = Array<Array<Field>>;
`Field[][]`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/rookModel.ts
> +        let reverse: number = this.color === Color.White ? 1 : -1;
`const`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Models/rookModel.ts
> +        let reverse: number = this.color === Color.White ? 1 : -1;
`const`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Views/boardView.ts
> +        let file = figure.color === Color.White ? 'w' : 'b';
Why not change the enums to match these filenames?

```
export enum Color {
    Black = 'b',
    White = 'w'
};

export enum FigureType {
    Rook = 'r',
    Tower = 't',
    Bishop = 'b',
    Knight = 'k',
    Queen = 'q',
    King = 'k'
};
```

Then you can simply do it like that:

`const file = figure.color + figure.name`

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Views/boardView.ts
> +        let file = figure.color === Color.White ? 'w' : 'b';
And that big switch is then not necessary

2021-01-31 14:58 UTC, Skorcese commented on src/ts/App/Controllers/boardController.ts
> +        this.attacksForSelected = null;
Note that you are using camelCase for properties here, but in other places there is snake_case. I know it comes from your Python habits, but in js/ts/node PascalCase and camelCase is used as a standard

2021-01-31 15:04 UTC, Skorcese commented
Where's the tsconfig.json?

2021-01-31 15:13 UTC, Skorcese commented on src/ts/App/Views/boardView.ts
> +        let file = figure.color === Color.White ? 'w' : 'b';
KISS & DRY :)

2021-01-31 15:32 UTC, kacus commented on src/ts/App/Controllers/boardController.ts
> +        this.attacksForSelected = null;
done

2021-01-31 15:32 UTC, kacus commented on src/ts/App/Views/boardView.ts
> +        let file = figure.color === Color.White ? 'w' : 'b';
done

2021-01-31 15:52 UTC, kacus commented on src/ts/App/Models/boardModel.ts
> +            [null, null, null, null, null, null, null, null],
It can't work as it should. Note that EMPTY_ROW is an array, so if we use it to populate an array there will be 6 copies of exactly this EMPTY_ROW, not 6 new empty arrays

2021-01-31 20:00 UTC, Skorcese requested changes

2021-01-31 20:03 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +            Array(8).fill(null),
More in the last comment

2021-01-31 20:03 UTC, Skorcese commented on src/ts/App/Models/boardModel.ts
> +        this.whiteKing = new KingModel(Color.White);
More in the last comment

2021-01-31 20:31 UTC, Skorcese commented
Furthermore. It's good to:

- move all your interfaces/types/enums to a separate files and folders. This way they are easier to find and don't clutter the Model directory
- prepend all interface/type/enum names with the first letter. For example interface IFigure, type TField or TListOfVectors, enum EColor or EFigureType. This will let others know immediately if it is an interface, type or enum

2021-02-01 17:24 UTC, kacus commented on src/ts/App/App.ts
> +    if (!!process.env.DEBUG) console.log('Start Chess App...');
You are right, I changed this because if DEBUG is undefined it can cause an error, i am going to figure this out

2021-02-01 17:27 UTC, kacus commented on src/ts/App/App.ts
> +    const controller = new BoardController(root!);
Right it should be in definition of root!

2021-02-01 17:27 UTC, kacus commented on src/ts/App/App.ts
> +    if (!!process.env.DEBUG) console.log('Start Chess App...');
I just notice, i can use exclamation mark to solve this problem :P

2021-02-01 17:37 UTC, kacus commented on src/ts/App/Models/boardModel.ts
> +        this.whiteKing = new KingModel(Color.White);
Sounds good, but if we want to start a new game we have to set up the whole board anyway

2021-02-01 20:24 UTC, merged